version: "3.9"

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db_data/postgres-data:/var/lib/postgresql/data

  # python-api:
  #   platform: "linux/amd64"
  #   build: .
  #   restart: always
  #   depends_on: 
  #     - db
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - .:/usr/src/diploma    
  #   command: ["python", "-m", "api"]